\include "helpers.ly"

\include "scores/beau_nash.ly"
\include "scores/cwm_felin.ly"
\include "scores/dyfatty_sheppans.ly"
\include "scores/dywetydd.ly"
\include "scores/march_a.ly"
\include "scores/march_b.ly"
\include "scores/march_c.ly"
\include "scores/mumbles_hornpipe.ly"
\include "scores/rita_nant.ly"
\include "scores/swansea_hornpipe.ly"
\include "scores/tom_rosser.ly"
\include "scores/valparaiso.ly"